spring:
  name: test
  activate:
    on-profile: test
  datasource:
    platform: h2
    url: jdbc:h2:mem:envDb;DATABASE_TO_LOWER=TRUE
    username: testUser
    password: testUser
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    changelog: classpath:/db/master-changelog.xml
    contexts: test
#    secureParsing: false
  #    url: mongodb://hostname:27017/test-enviroment
  jpa:
    show-sql: true
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: test-enviroment
      port: 27017
      host: localhost
      auto-index-creation: true